package langconv

import "strings"

// langToISO6391Map maps language names to their ISO 639-1 codes
var langToISO6391Map = map[string]string{
	"abkhazian":         "ab",
	"afar":              "aa",
	"afrikaans":         "af",
	"akan":              "ak",
	"albanian":          "sq",
	"amharic":           "am",
	"arabic":            "ar",
	"armenian":          "hy",
	"assamese":          "as",
	"aymara":            "ay",
	"azerbaijani":       "az",
	"bambara":           "bm",
	"bashkir":           "ba",
	"basque":            "eu",
	"belarusian":        "be",
	"bengali":           "bn",
	"bihari":            "bh",
	"bislama":           "bi",
	"bosnian":           "bs",
	"breton":            "br",
	"bulgarian":         "bg",
	"burmese":           "my",
	"catalan":           "ca",
	"chamorro":          "ch",
	"chechen":           "ce",
	"chichewa":          "ny",
	"chinese":           "zh",
	"church slavic":     "cu",
	"chuvash":           "cv",
	"cornish":           "kw",
	"corsican":          "co",
	"cree":              "cr",
	"croatian":          "hr",
	"czech":             "cs",
	"danish":            "da",
	"divehi":            "dv",
	"dutch":             "nl",
	"dzongkha":          "dz",
	"english":           "en",
	"esperanto":         "eo",
	"estonian":          "et",
	"ewe":               "ee",
	"faroese":           "fo",
	"fijian":            "fj",
	"finnish":           "fi",
	"french":            "fr",
	"fulah":             "ff",
	"gaelic":            "gd",
	"galician":          "gl",
	"ganda":             "lg",
	"georgian":          "ka",
	"german":            "de",
	"greek":             "el",
	"guarani":           "gn",
	"gujarati":          "gu",
	"haitian":           "ht",
	"hausa":             "ha",
	"hebrew":            "he",
	"herero":            "hz",
	"hindi":             "hi",
	"hiri motu":         "ho",
	"hungarian":         "hu",
	"icelandic":         "is",
	"ido":               "io",
	"igbo":              "ig",
	"indonesian":        "id",
	"interlingua":       "ia",
	"interlingue":       "ie",
	"inuktitut":         "iu",
	"inupiaq":           "ik",
	"irish":             "ga",
	"italian":           "it",
	"japanese":          "ja",
	"javanese":          "jv",
	"kannada":           "kn",
	"kanuri":            "kr",
	"kashmiri":          "ks",
	"kazakh":            "kk",
	"khmer":             "km",
	"kikuyu":            "ki",
	"kinyarwanda":       "rw",
	"kirghiz":           "ky",
	"komi":              "kv",
	"kongo":             "kg",
	"korean":            "ko",
	"kuanyama":          "kj",
	"kurdish":           "ku",
	"lao":               "lo",
	"latin":             "la",
	"latvian":           "lv",
	"limburgan":         "li",
	"lingala":           "ln",
	"lithuanian":        "lt",
	"luba-katanga":      "lu",
	"luxembourgish":     "lb",
	"macedonian":        "mk",
	"malagasy":          "mg",
	"malay":             "ms",
	"malayalam":         "ml",
	"maltese":           "mt",
	"manx":              "gv",
	"maori":             "mi",
	"marathi":           "mr",
	"marshallese":       "mh",
	"mongolian":         "mn",
	"nauru":             "na",
	"navajo":            "nv",
	"ndonga":            "ng",
	"nepali":            "ne",
	"north ndebele":     "nd",
	"northern sami":     "se",
	"norwegian":         "no",
	"norwegian bokmål":  "nb",
	"norwegian nynorsk": "nn",
	"nuosu":             "ii",
	"occitan":           "oc",
	"ojibwa":            "oj",
	"oriya":             "or",
	"oromo":             "om",
	"ossetian":          "os",
	"pashto":            "ps",
	"persian":           "fa",
	"polish":            "pl",
	"portuguese":        "pt",
	"punjabi":           "pa",
	"quechua":           "qu",
	"romanian":          "ro",
	"romansh":           "rm",
	"rundi":             "rn",
	"russian":           "ru",
	"samoan":            "sm",
	"sango":             "sg",
	"sanskrit":          "sa",
	"sardinian":         "sc",
	"scottish gaelic":   "gd",
	"serbian":           "sr",
	"shona":             "sn",
	"sindhi":            "sd",
	"sinhala":           "si",
	"slovak":            "sk",
	"slovenian":         "sl",
	"somali":            "so",
	"sotho":             "st",
	"south ndebele":     "nr",
	"spanish":           "es",
	"sundanese":         "su",
	"swahili":           "sw",
	"swati":             "ss",
	"swedish":           "sv",
	"tagalog":           "tl",
	"tahitian":          "ty",
	"tajik":             "tg",
	"tamil":             "ta",
	"tatar":             "tt",
	"telugu":            "te",
	"thai":              "th",
	"tibetan":           "bo",
	"tigrinya":          "ti",
	"tongan":            "to",
	"tsonga":            "ts",
	"tswana":            "tn",
	"turkish":           "tr",
	"turkmen":           "tk",
	"twi":               "tw",
	"uyghur":            "ug",
	"ukrainian":         "uk",
	"urdu":              "ur",
	"uzbek":             "uz",
	"venda":             "ve",
	"vietnamese":        "vi",
	"volapük":           "vo",
	"walloon":           "wa",
	"welsh":             "cy",
	"western frisian":   "fy",
	"wolof":             "wo",
	"xhosa":             "xh",
	"yiddish":           "yi",
	"yoruba":            "yo",
	"zhuang":            "za",
	"zulu":              "zu",
}

// GetISO6391Code converts a language name to its ISO 639-1 code
func GetISO6391Code(languageName string) (string, bool) {
	// Convert the input to lowercase to ensure case-insensitive matching
	code, found := langToISO6391Map[strings.ToLower(languageName)]
	return code, found
}
