package langconv

import "strings"

type Language struct {
	Code    string
	TitleRu string
}

var langToISO6391Map = map[string]Language{
	"abkhazian":                        {Code: "ab", TitleRu: "Абхазский"},
	"afar":                             {Code: "aa", TitleRu: "Афарский"},
	"afrikaans":                        {Code: "af", TitleRu: "Африкаанс"},
	"akan":                             {Code: "ak", TitleRu: "Акан"},
	"albanian":                         {Code: "sq", TitleRu: "Албанский"},
	"amharic":                          {Code: "am", TitleRu: "Амхарский"},
	"arabic":                           {Code: "ar", TitleRu: "Арабский"},
	"armenian":                         {Code: "hy", TitleRu: "Армянский"},
	"assamese":                         {Code: "as", TitleRu: "Ассамский"},
	"avaric":                           {Code: "av", TitleRu: "Аварский"},
	"avestan":                          {Code: "ae", TitleRu: "Авестийский"},
	"aymara":                           {Code: "ay", TitleRu: "Аймара"},
	"azerbaijani":                      {Code: "az", TitleRu: "Азербайджанский"},
	"bashkir":                          {Code: "ba", TitleRu: "Башкирский"},
	"bambara":                          {Code: "bm", TitleRu: "Бамбара"},
	"belarusian":                       {Code: "be", TitleRu: "Белорусский"},
	"bengali":                          {Code: "bn", TitleRu: "Бенгальский"},
	"bihari languages":                 {Code: "bh", TitleRu: "Бихари"},
	"bislama":                          {Code: "bi", TitleRu: "Бислама"},
	"tibetan":                          {Code: "bo", TitleRu: "Тибетский"},
	"bosnian":                          {Code: "bs", TitleRu: "Боснийский"},
	"breton":                           {Code: "br", TitleRu: "Бретонский"},
	"bulgarian":                        {Code: "bg", TitleRu: "Болгарский"},
	"burmese":                          {Code: "my", TitleRu: "Бирманский"},
	"catalan":                          {Code: "ca", TitleRu: "Каталанский"},
	"czech":                            {Code: "cs", TitleRu: "Чешский"},
	"chamorro":                         {Code: "ch", TitleRu: "Чаморро"},
	"chechen":                          {Code: "ce", TitleRu: "Чеченский"},
	"chichewa":                         {Code: "ny", TitleRu: "Чичева"},
	"chinese":                          {Code: "zh", TitleRu: "Китайский"},
	"church slavic":                    {Code: "cu", TitleRu: "Церковнославянский"},
	"chuvash":                          {Code: "cv", TitleRu: "Чувашский"},
	"cornish":                          {Code: "kw", TitleRu: "Корнский"},
	"corsican":                         {Code: "co", TitleRu: "Корсиканский"},
	"cree":                             {Code: "cr", TitleRu: "Кри"},
	"danish":                           {Code: "da", TitleRu: "Датский"},
	"german":                           {Code: "de", TitleRu: "Немецкий"},
	"divali":                           {Code: "dv", TitleRu: "Дивехи"},
	"dzongkha":                         {Code: "dz", TitleRu: "Дзонг-кэ"},
	"greek":                            {Code: "el", TitleRu: "Греческий"},
	"english":                          {Code: "en", TitleRu: "Английский"},
	"esperanto":                        {Code: "eo", TitleRu: "Эсперанто"},
	"estonian":                         {Code: "et", TitleRu: "Эстонский"},
	"ewe":                              {Code: "ee", TitleRu: "Эве"},
	"faroese":                          {Code: "fo", TitleRu: "Фарерский"},
	"fijian":                           {Code: "fj", TitleRu: "Фиджи"},
	"finnish":                          {Code: "fi", TitleRu: "Финский"},
	"french":                           {Code: "fr", TitleRu: "Французский"},
	"fulah":                            {Code: "ff", TitleRu: "Фулах"},
	"georgian":                         {Code: "ka", TitleRu: "Грузинский"},
	"gaelic":                           {Code: "gd", TitleRu: "Гэльский"},
	"irish":                            {Code: "ga", TitleRu: "Ирландский"},
	"galician":                         {Code: "gl", TitleRu: "Галисийский"},
	"manx":                             {Code: "gv", TitleRu: "Мэнский"},
	"guarani":                          {Code: "gn", TitleRu: "Гуарани"},
	"gujarati":                         {Code: "gu", TitleRu: "Гуджарати"},
	"haitian; haitian creole":          {Code: "ht", TitleRu: "Гаитянский"},
	"hausa":                            {Code: "ha", TitleRu: "Хауса"},
	"hebrew (modern)":                  {Code: "he", TitleRu: "Иврит"},
	"herero":                           {Code: "hz", TitleRu: "Гереро"},
	"hindi":                            {Code: "hi", TitleRu: "Хинди"},
	"hiri motu":                        {Code: "ho", TitleRu: "Хиримоту"},
	"croatian":                         {Code: "hr", TitleRu: "Хорватский"},
	"hungarian":                        {Code: "hu", TitleRu: "Венгерский"},
	"icelandic":                        {Code: "is", TitleRu: "Исландский"},
	"ido":                              {Code: "io", TitleRu: "Идо"},
	"sichuan yi; nuosu":                {Code: "ii", TitleRu: "Носу"},
	"inuktitut":                        {Code: "iu", TitleRu: "Инуктитут"},
	"interlingue occidental":           {Code: "ie", TitleRu: "Интерлингве"},
	"interlingua international":        {Code: "ia", TitleRu: "Интерлингва"},
	"indonesian":                       {Code: "id", TitleRu: "Индонезийский"},
	"inupiaq":                          {Code: "ik", TitleRu: "Инупиак"},
	"italian":                          {Code: "it", TitleRu: "Итальянский"},
	"javanese":                         {Code: "jv", TitleRu: "Яванский"},
	"japanese":                         {Code: "ja", TitleRu: "Японский"},
	"kalaallisut; greenlandic":         {Code: "kl", TitleRu: "Гренландский"},
	"kannada":                          {Code: "kn", TitleRu: "Каннада"},
	"kashmiri":                         {Code: "ks", TitleRu: "Кашмири"},
	"kanuri":                           {Code: "kr", TitleRu: "Канури"},
	"kazakh":                           {Code: "kk", TitleRu: "Казахский"},
	"central khmer":                    {Code: "km", TitleRu: "Кхмерский"},
	"kikuyu; gikuyu":                   {Code: "ki", TitleRu: "Кикуйю"},
	"kinyarwanda":                      {Code: "rw", TitleRu: "Киньяруанда"},
	"kirghiz; kyrgyz":                  {Code: "ky", TitleRu: "Киргизский"},
	"komi":                             {Code: "kv", TitleRu: "Коми"},
	"kongo":                            {Code: "kg", TitleRu: "Конго"},
	"korean":                           {Code: "ko", TitleRu: "Корейский"},
	"kuanyama; kwanyama":               {Code: "kj", TitleRu: "Кваньяма"},
	"kurdish":                          {Code: "ku", TitleRu: "Курдский"},
	"lao":                              {Code: "lo", TitleRu: "Лаосский"},
	"latin":                            {Code: "la", TitleRu: "Латинский"},
	"latvian":                          {Code: "lv", TitleRu: "Латышский"},
	"limburgan; limburger; limburgish": {Code: "li", TitleRu: "Лимбургский"},
	"lingala":                          {Code: "ln", TitleRu: "Лингала"},
	"lithuanian":                       {Code: "lt", TitleRu: "Литовский"},
	"luba-lulua":                       {Code: "lu", TitleRu: "Луба-катанга"},
	"luxembourgish; letzeburgesch":     {Code: "lb", TitleRu: "Люксембургский"},
	"ganda":                            {Code: "lg", TitleRu: "Ганда"},
	"marshallese":                      {Code: "mh", TitleRu: "Маршалльский"},
	"malayalam":                        {Code: "ml", TitleRu: "Малаялам"},
	"marathi":                          {Code: "mr", TitleRu: "Маратхи"},
	"malay":                            {Code: "ms", TitleRu: "Малайский"},
	"malagasy":                         {Code: "mg", TitleRu: "Малагасийский"},
	"maltese":                          {Code: "mt", TitleRu: "Мальтийский"},
	"mongolian":                        {Code: "mn", TitleRu: "Монгольский"},
	"nauru":                            {Code: "na", TitleRu: "Науру"},
	"navajo; navaho":                   {Code: "nv", TitleRu: "Навахо"},
	"ndebele, north; north ndebele":    {Code: "nd", TitleRu: "Северный ндебеле"},
	"ndebele, south; south ndebele":    {Code: "nr", TitleRu: "Южный ндебеле"},
	"ndonga":                           {Code: "ng", TitleRu: "Ндонга"},
	"nepali":                           {Code: "ne", TitleRu: "Непальский"},
	"norwegian":                        {Code: "no", TitleRu: "Норвежский"},
	"norwegian bokmål":                 {Code: "nb", TitleRu: "Норвежский букмол"},
	"norwegian nynorsk":                {Code: "nn", TitleRu: "Норвежский нюнорск"},
	"occitan (post 1500); provencal":   {Code: "oc", TitleRu: "Окситанский"},
	"ojibwa":                           {Code: "oj", TitleRu: "Оджибва"},
	"oriya":                            {Code: "or", TitleRu: "Ория"},
	"ossetian; ossetic":                {Code: "os", TitleRu: "Осетинский"},
	"panjabi; punjabi":                 {Code: "pa", TitleRu: "Панджаби"},
	"pali":                             {Code: "pi", TitleRu: "Пали"},
	"persian":                          {Code: "fa", TitleRu: "Персидский"},
	"polish":                           {Code: "pl", TitleRu: "Польский"},
	"portuguese":                       {Code: "pt", TitleRu: "Португальский"},
	"pushto; pashto":                   {Code: "ps", TitleRu: "Пушту"},
	"quechua":                          {Code: "qu", TitleRu: "Кечуа"},
	"romansh":                          {Code: "rm", TitleRu: "Ретороманский"},
	"romanian; moldavian; moldovan":    {Code: "ro", TitleRu: "Румынский"},
	"rundi":                            {Code: "rn", TitleRu: "Рунди"},
	"russian":                          {Code: "ru", TitleRu: "Русский"},
	"sango":                            {Code: "sg", TitleRu: "Санго"},
	"sanskrit":                         {Code: "sa", TitleRu: "Санскрит"},
	"sardinian":                        {Code: "sc", TitleRu: "Сардинский"},
	"sindhi":                           {Code: "sd", TitleRu: "Синдхи"},
	"northern sami":                    {Code: "se", TitleRu: "Северный саамский"},
	"samoan":                           {Code: "sm", TitleRu: "Самоанский"},
	"serbian":                          {Code: "sr", TitleRu: "Сербский"},
	"gaelic;":                          {Code: "gd", TitleRu: "Гэльский"},
	"shona":                            {Code: "sn", TitleRu: "Шона"},
	"sinhala; sinhalese":               {Code: "si", TitleRu: "Сингальский"},
	"slovak":                           {Code: "sk", TitleRu: "Словацкий"},
	"slovenian":                        {Code: "sl", TitleRu: "Словенский"},
	"somali":                           {Code: "so", TitleRu: "Сомали"},
	"sotho, southern":                  {Code: "st", TitleRu: "Южный сото"},
	"spanish; castilian":               {Code: "es", TitleRu: "Испанский"},
	"sundanese":                        {Code: "su", TitleRu: "Сунданский"},
	"swahili":                          {Code: "sw", TitleRu: "Суахили"},
	"swati":                            {Code: "ss", TitleRu: "Свази"},
	"swedish":                          {Code: "sv", TitleRu: "Шведский"},
	"tagalog":                          {Code: "tl", TitleRu: "Тагальский"},
	"tahitian":                         {Code: "ty", TitleRu: "Таитянский"},
	"tajik":                            {Code: "tg", TitleRu: "Таджикский"},
	"tamil":                            {Code: "ta", TitleRu: "Тамильский"},
	"tatar":                            {Code: "tt", TitleRu: "Татарский"},
	"telugu":                           {Code: "te", TitleRu: "Телугу"},
	"thai":                             {Code: "th", TitleRu: "Тайский"},
	"tigrinya":                         {Code: "ti", TitleRu: "Тигринья"},
	"tonga (tonga islands)":            {Code: "to", TitleRu: "Тонганский"},
	"tsonga":                           {Code: "ts", TitleRu: "Тсонга"},
	"tswana":                           {Code: "tn", TitleRu: "Тсвана"},
	"turkish":                          {Code: "tr", TitleRu: "Турецкий"},
	"turkmen":                          {Code: "tk", TitleRu: "Туркменский"},
	"twi":                              {Code: "tw", TitleRu: "Тви"},
	"uighur":                           {Code: "ug", TitleRu: "Уйгурский"},
	"ukrainian":                        {Code: "uk", TitleRu: "Украинский"},
	"urdu":                             {Code: "ur", TitleRu: "Урду"},
	"uzbek":                            {Code: "uz", TitleRu: "Узбекский"},
	"venda":                            {Code: "ve", TitleRu: "Венда"},
	"vietnamese":                       {Code: "vi", TitleRu: "Вьетнамский"},
	"volapük":                          {Code: "vo", TitleRu: "Волапюк"},
	"walloon":                          {Code: "wa", TitleRu: "Валлонский"},
	"welsh":                            {Code: "cy", TitleRu: "Валлийский"},
	"wolof":                            {Code: "wo", TitleRu: "Волоф"},
	"western frisian":                  {Code: "fy", TitleRu: "Западно-фризский"},
	"xhosa":                            {Code: "xh", TitleRu: "Коса"},
	"yiddish":                          {Code: "yi", TitleRu: "Идиш"},
	"yoruba":                           {Code: "yo", TitleRu: "Йоруба"},
	"zhuang":                           {Code: "za", TitleRu: "Чжуанский"},
	"zulu":                             {Code: "zu", TitleRu: "Зулу"},
}

// GetISO6391Code converts a language name to its ISO 639-1 code
func GetISO6391Code(languageName string) (Language, bool) {
	// Convert the input to lowercase to ensure case-insensitive matching
	code, found := langToISO6391Map[strings.ToLower(languageName)]
	return code, found
}
